# fly.toml app configuration file generated for financio-api on 2026-03-06T09:26:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'financio-api'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  BACKEND_PORT = '8080'
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
