export const Resources = {
  title: 'Create Account',
  subtitle: 'Register to start using Financio',
  usernameLabel: 'Username',
  usernamePlaceholder: 'Choose a username',
  emailLabel: 'Email',
  emailPlaceholder: 'you@example.com',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Create a password',
  confirmPasswordLabel: 'Confirm Password',
  confirmPasswordPlaceholder: 'Repeat your password',
  firstNameLabel: 'First Name',
  firstNamePlaceholder: 'John',
  lastNameLabel: 'Last Name',
  lastNamePlaceholder: 'Doe',
  submitButton: 'Create Account',
  loadingButton: 'Creating account...',
  hasAccount: 'Already have an account?',
  loginLink: 'Sign in',
  validation: {
    usernameRequired: 'Username is required',
    usernameMinLength: 'Username must be at least 3 characters',
    usernamePattern: 'Username can only contain letters, numbers, and underscores',
    emailRequired: 'Email is required',
    emailInvalid: 'Please enter a valid email',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 8 characters',
    confirmPasswordRequired: 'Please confirm your password',
    confirmPasswordMismatch: 'Passwords do not match',
  },
} as const;
